---
- name: Create the configurations for sites
  template:
    src: "{{ item.value.template | default('site.conf.j2') }}"
    dest: "{{ nginx_conf_dir }}/sites-available/{{ item.key }}.conf"
  with_dict: "{{ nginx_sites }}"
  when: item.key not in nginx_remove_sites
  notify:
   - reload nginx

- name: Create links for sites-enabled
  file:
    state: link
    src: "{{ nginx_conf_dir }}/sites-available/{{ item.key }}.conf"
    dest: "{{ nginx_conf_dir }}/sites-enabled/{{ item.key }}.conf"
  with_dict: "{{ nginx_sites }}"
  when: item.key not in nginx_remove_sites
  notify:
   - reload nginx

- name: Remove unwanted sites
  file:
    path: "{{nginx_conf_dir}}/{{ item[0] }}/{{ item[1] }}.conf"
    state: absent
  with_nested:
    - [ 'sites-enabled', 'sites-available']
    - "{{ nginx_remove_sites }}"
  notify:
   - reload nginx
