---
- name: Prepare
  hosts: all
  gather_facts: True
  roles:
    - name: jdauphant.nginx
      nginx_sites:
        default:
          - listen 80 default_server
          - server_name _
          - root "{% if ansible_os_family == 'FreeBSD' %}/usr/local/www/nginx-dist{% else %}/usr/share/nginx/html{% endif %}"
          - index index.html
